### ISSUE TITLE
Add Storage Options for TubeSync

### ISSUE THREAD

**Issue by Makr91** [jdeath/homeassistant-addons#18]
The current configuration stores this in the /usr/share/hassio/homeassistant/addon_configs/tubesync/.../.../etc

By doing this it creates massive HomeAssistant Backups. I have currently worked around this a little bit. However I would like to see more options added to the configurations of this if possible.

**Comment by jdeath** [comment]
I tried something quick to move downloads to /share/tubesync/ but it didn't work. I'll try a few other things later. Best way is to ask the developer if the download directory can be set via an environment variable. Without that, it may be beyond my skills to redirect it.

**Comment by Makr91** [comment]
Thanks for entertaining the idea.

In other Home Assitant Add-Ons, They include they expose the map option so that you can map the shares (for example a NFS Storage share)

  "map": [
    "config:rw",
    "share:rw",
    "media:rw",
    "ssl"
  ],

in the config.json. However I am not sure how to expose options. 

I can add options to the Dockerfile for some things but I don't think thats the right way to do it

**Comment by jdeath** [comment]
Are your files not in /config/addons_config/tubesync ? Not sure when in /usr/local, do you not use HASSOS? I do not have experience with any other installs.

Yes, you are on the right path. I will not make an update, because it could break other people's installations. However, if you want to move everything to /media you can do this. There is an option in homeassistant to not backup media

Download this repo. Copy tubsync folder to /addons/
replace the sed line in the Dockerfile to this:
RUN sed -i 's/Path('\''\/'\'')/Path('\''\/media\/tubesync\/'\'')/' /app/tubesync/local_settings.py 

Add the mapping line in config.json like you did above. You only need the media:rw line. Remember, last entry in the list does not have a ,

Hopefully you can copy your existing tubesync directory to /media/ 

The permissions get all messed up when running from media. In a hassio command line (ssh addon)
chgrp -R hassio /media/tubesync/
chown -R 911 /media/tubesync/

If moving things over does not work, then need to start fresh:
mkdir /media/tubesync
mkdir /media/tubesync/config
mkdir /media/tubesync/downloads
chgrp -R hassio /media/tubesync/
chown -R 911 /media/tubesync/

Goodluck

**Comment by Makr91** [comment]
No I don't use HASSOS. I prefer to run everything off my own Debian Templates. I use the Supervised Method of install home assistant. If I had my way I'd still use Core, but the HA team is making it harder and harder to run Core and Supervised. 

The default location of supervised is to install Home assistant into /usr/share/hassio/homeassistant 

Inside of the Tubesync container, yes the files are in the path you mentioned, but because of that, I get Backups that are several Gigabytes in size.

I suppose I will just fork this repo and maintain my own Add-On's. It would have been nice out of the box to store the media into the dedicated /share partitions that are made when you create a Home Assistant Storage object.

Thanks again for the detailed breakdown.
