### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ChristoffBo** [jdeath/homeassistant-addons#2]
Hi,

Was wondering if you can assist i created an addon for technitium DNS

but for the life of me i cant get persistant data across addon restarts?

Would greatly appreciate assistance

https://github.com/ChristoffBo/hassio-addons/blob/main/technitium

**Comment by jdeath** [comment]
The issue is the docker file you are using wants to store configuration in: /etc/dns/config/ and wants you to create a volume to do so (you can see in https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml) . But you cant with homeassistant. Getting this to work is hit and miss,. You could try to create a symbolic link. Thus your run.sh should try to: 
mkdir -p /data/technitium (you did this)
ln -s /data/technitium /etc/dns/config/ (or vice versa, I forget)
/usr/bin/dotnet /etc/dns/DnsServerApp.dll (I think you need this, but maybe not)

This is a common issue. Again, the link method might not work and is a pain as you need to rebuild the addon every time to test it. You could also email the author of technitium and ask him/her to allow setting the configuration directory via an environmental variable. Then you could set it to whatever you want. that would be much easier. Good luck

**Comment by ChristoffBo** [comment]
Hi, awesome will ask them to create an image. Thanks for your quick and friendly reply

Christoff Bothma
Sent From Mobile
________________________________
