### ISSUE TITLE
SHIORI - Cannot open from sidebar or "open web ui"

### ISSUE THREAD

**Issue by michaelblight** [jdeath/homeassistant-addons#36]
I can go to the URL:port and it works, but if I enable showing in sidebar, or click "open web ui" it just opens a black page (dark mode for me probably). Is this expected or a bug?

Also, the documentation talks about connecting to the container with "/bin/sh", but it's not installed with the docker image (perhaps it was in an older version). Therefore I can't do "shiori migrate" and I don't know if this is important or not.

**Comment by jdeath** [comment]
Ingress no longer works (not sure if it ever worked), so the sidebar/WebUI will not work. You will have to go to homeassistantIP:port to get to the interface. I will remove the ingress option to avoid confusion.

They must have removed sh from the image. I think the migrate command was only needed a while ago. However, you can still run CLI this way:
`docker exec -it containerID command`
like
`docker exec -it containerID shiori add --help`

I may try to update this so it stores information in addon_config instead of in the container.
